#!/bin/bash
RED='\033[0;31m'
NC='\033[0m'
path=$(pwd)
printf "${RED}[Script] Installing pre-requisites...${NC}\n"
sudo apt-get install git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
printf "${RED}[Script] Creating esp folder...${NC}\n"
mkdir -p ./esp
cd ./esp
printf "${RED}[Script] Downloading IDF${NC}\n"
git clone --recursive https://github.com/espressif/esp-idf.git
printf "${RED}[Script] Installing IDF${NC}\n"
cd ./esp-idf
./install.sh esp32
printf "${RED}[Script] Aliasing IDF to bashrc...${NC}\n"
echo "alias get_idf='. ${path}/esp/esp-idf/export.sh'" >> ~/.bashrc
printf "${RED}[Script] Done! Simply run 'source ~/.bashrc' and 'get_idf' to start${NC}\n"
